//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public string baslik { get; set; }
        public string tarih { get; set; }
        public string icerik { get; set; }
        public int CategoryId { get; set; }
        public int UserSetId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual UserSet UserSet { get; set; }
    }
}
